### ISSUE TITLE
Make services header sticky while scrolling through services.

### ISSUE THREAD

**Issue by bsommardahl** [bsommardahl/herounit.io#15]
When you scroll down through the services, you lose context of the columns. It would be great if the header of the services could stay on the screen until you scroll down to "Strategy" in the "Additional Services" section. Then it could go ahead and scroll up.

**Comment by wilmermurillo** [comment]
Issue fixed:
https://github.com/bsommardahl/herounit.io/commit/2c8fa0173e06895a4854270229870b281622e78d

**Comment by bsommardahl** [comment]
This issue is for the services table, not the page header.

**Comment by wilmermurillo** [comment]
#23 Fixed - Added sticky position to the table header.
