### ISSUE TITLE
"Request a Quote" loads slowly the first time

### ISSUE THREAD

**Issue by bsommardahl** [bsommardahl/herounit.io#19]
Maybe there's no way to speed up the load of the quote form, but it might be good to have a loading indicator. The first time I saw it, I thought it was a mistake and hit reload before it could load all the way.

**Comment by bsommardahl** [comment]
https://cl.ly/7554f9368c30

**Comment by wilmermurillo** [comment]
Fixed here:
https://github.com/bsommardahl/herounit.io/commit/2c8fa0173e06895a4854270229870b281622e78d

Now it loads after scrolling 300px.
