### ISSUE TITLE
Change advisory services.

### ISSUE THREAD

**Issue by bsommardahl** [bsommardahl/herounit.io#20]
CTO calls should be 1 and 2 per month for premium and gold.

**Comment by wilmermurillo** [comment]
And for Product Manager it is 0 for basic, 1 for basic and 2 for gold, right?

**Comment by bsommardahl** [comment]
For this change, it should be 0,1,2 for CTO calls

Not sure about project manager calls.

**Comment by wilmermurillo** [comment]
Got it, thank you!

**Comment by wilmermurillo** [comment]
Oh, sorry I missed this last reply before the deploy. Fixing it now and going thru next deploy.

**Comment by wilmermurillo** [comment]
#24 Fixed.
