### ISSUE TITLE
Update "Credit-based Maintenance"

### ISSUE THREAD

**Issue by bsommardahl** [bsommardahl/herounit.io#22]
Change to:

> Your team will follow your lead, spending credits from your bucket each month. It’s up to you what they work on and when. One credit is the same as one hour if the team uses it during normal USA business hours. But you have the flexibility to use credits at other times as well.

**Comment by wilmermurillo** [comment]
Updated #23

**Comment by wilmermurillo** [comment]
#23 Fixed.
